#
# freebsd.sh config file
#

EXTERNAL_NETWORK="10.211.55"
EXTERNAL_NETMASK="10.211.55.0/24"

FIREWALL_OUTBOUND_ALL="yes"

FIREWALL_CLIENT_DHCP="yes"

FIREWALL_EXTERNAL_SSH="yes"
FIREWALL_SSH_PORT="6666"

FIREWALL_BLACKLIST="yes"
BLACKLIST_NETWORK="10.211.55"

FIREWALL_BLACKHOLE="yes"
