#
# Generic Firewall config for simple client host
#

EXTERNAL_INTERFACE="eth0"
EXTERNAL_NETMASK="10.211.55.0/24"

FIREWALL_CLIENT_DHCP="yes"
FIREWALL_SERVER_SSH="yes"

FIREWALL_BLOCK_SMB="yes"
FIREWALL_BLOCK_DOMAIN="yes"
FIREWALL_BLOCK_HTTP="yes"
FIREWALL_BLOCK_GENERIC="yes"
FIREWALL_BLOCK_FTP="yes"


