#
# Generic Firewall config for simple client host
#

EXTERNAL_INTERFACE="eth0"
EXTERNAL_NETMASK="10.211.55.0/24"

LOOPBACK_NETMASK="127.0.0.0/8"

FIREWALL_CLIENT_DHCP="yes"
FIREWALL_SERVER_SSH="yes"
FIREWALL_OUTBOUND_ALL="yes"

FIREWALL_BLOCK_SMB="yes"
FIREWALL_BLOCK_DOMAIN="yes"
FIREWALL_BLOCK_HTTP="yes"
FIREWALL_BLOCK_GENERIC="yes"
FIREWALL_BLOCK_FTP="yes"

FIREWALL_SSH_PORT="6666"
FIREWALL_SSH_CAP="10"
FIREWALL_SSH_THROTTLE="5"

FIREWALL_SERVICE_CAP="20"
FIREWALL_SERVICE_THROTTLE="10"




